
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author karee
 */
public class GamePage extends javax.swing.JFrame {

    public static boolean lost;
    
    /**
     * Creates new form GamePage
     */
    public GamePage() {
        initComponents();
        lost = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        word1panel1 = new javax.swing.JPanel();
        word1label1 = new javax.swing.JLabel();
        word1panel2 = new javax.swing.JPanel();
        word1label2 = new javax.swing.JLabel();
        word1panel3 = new javax.swing.JPanel();
        word1label3 = new javax.swing.JLabel();
        word1panel4 = new javax.swing.JPanel();
        word1label4 = new javax.swing.JLabel();
        word1panel5 = new javax.swing.JPanel();
        word1label5 = new javax.swing.JLabel();
        word2panel1 = new javax.swing.JPanel();
        word2label1 = new javax.swing.JLabel();
        word2panel2 = new javax.swing.JPanel();
        word2label2 = new javax.swing.JLabel();
        word2panel3 = new javax.swing.JPanel();
        word2label3 = new javax.swing.JLabel();
        word2panel4 = new javax.swing.JPanel();
        word2label4 = new javax.swing.JLabel();
        word2panel5 = new javax.swing.JPanel();
        word2label5 = new javax.swing.JLabel();
        word3panel1 = new javax.swing.JPanel();
        word3label1 = new javax.swing.JLabel();
        word3panel2 = new javax.swing.JPanel();
        word3label2 = new javax.swing.JLabel();
        word3panel3 = new javax.swing.JPanel();
        word3label3 = new javax.swing.JLabel();
        word3panel4 = new javax.swing.JPanel();
        word3label4 = new javax.swing.JLabel();
        word3panel5 = new javax.swing.JPanel();
        word3label5 = new javax.swing.JLabel();
        word4panel1 = new javax.swing.JPanel();
        word4label1 = new javax.swing.JLabel();
        word4panel2 = new javax.swing.JPanel();
        word4label2 = new javax.swing.JLabel();
        word4panel3 = new javax.swing.JPanel();
        word4label3 = new javax.swing.JLabel();
        word4panel4 = new javax.swing.JPanel();
        word4label4 = new javax.swing.JLabel();
        word4panel5 = new javax.swing.JPanel();
        word4label5 = new javax.swing.JLabel();
        word5panel1 = new javax.swing.JPanel();
        word5label1 = new javax.swing.JLabel();
        word5panel2 = new javax.swing.JPanel();
        word5label2 = new javax.swing.JLabel();
        word5panel3 = new javax.swing.JPanel();
        word5label3 = new javax.swing.JLabel();
        word5panel4 = new javax.swing.JPanel();
        word5label4 = new javax.swing.JLabel();
        word5panel5 = new javax.swing.JPanel();
        word5label5 = new javax.swing.JLabel();
        word6panel1 = new javax.swing.JPanel();
        word6label1 = new javax.swing.JLabel();
        word6panel2 = new javax.swing.JPanel();
        word6label2 = new javax.swing.JLabel();
        word6panel3 = new javax.swing.JPanel();
        word6label3 = new javax.swing.JLabel();
        word6panel4 = new javax.swing.JPanel();
        word6label4 = new javax.swing.JLabel();
        word6panel5 = new javax.swing.JPanel();
        word6label5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        HomeButton = new javax.swing.JButton();
        EnterButton1 = new javax.swing.JButton();

        jDialog1.setTitle("ERROR");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 230, 100));
        jDialog1.setMaximumSize(new java.awt.Dimension(215, 65));
        jDialog1.setMinimumSize(new java.awt.Dimension(215, 65));
        jDialog1.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(67, 67, 67));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Must enter a valid 5 letter word.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog2.setTitle("ERROR");
        jDialog2.setAlwaysOnTop(true);
        jDialog2.setBounds(new java.awt.Rectangle(0, 0, 230, 100));
        jDialog2.setMaximumSize(new java.awt.Dimension(215, 65));
        jDialog2.setMinimumSize(new java.awt.Dimension(215, 65));
        jDialog2.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(67, 67, 67));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Must enter a valid 5 letter word.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Walmart Wordle");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(67, 67, 67));
        jPanel1.setMaximumSize(new java.awt.Dimension(370, 496));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 496));

        word1panel1.setBackground(new java.awt.Color(144, 144, 144));
        word1panel1.setFocusable(false);
        word1panel1.setMaximumSize(new java.awt.Dimension(50, 50));
        word1panel1.setMinimumSize(new java.awt.Dimension(50, 50));

        word1label1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word1label1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word1panel1Layout = new javax.swing.GroupLayout(word1panel1);
        word1panel1.setLayout(word1panel1Layout);
        word1panel1Layout.setHorizontalGroup(
            word1panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word1panel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word1label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word1panel1Layout.setVerticalGroup(
            word1panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word1label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        word1panel2.setBackground(new java.awt.Color(144, 144, 144));
        word1panel2.setMaximumSize(new java.awt.Dimension(50, 50));
        word1panel2.setMinimumSize(new java.awt.Dimension(50, 50));

        word1label2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word1label2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word1panel2Layout = new javax.swing.GroupLayout(word1panel2);
        word1panel2.setLayout(word1panel2Layout);
        word1panel2Layout.setHorizontalGroup(
            word1panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word1panel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word1label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word1panel2Layout.setVerticalGroup(
            word1panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word1label2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word1panel3.setBackground(new java.awt.Color(144, 144, 144));
        word1panel3.setMaximumSize(new java.awt.Dimension(50, 50));
        word1panel3.setMinimumSize(new java.awt.Dimension(50, 50));

        word1label3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word1label3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word1panel3Layout = new javax.swing.GroupLayout(word1panel3);
        word1panel3.setLayout(word1panel3Layout);
        word1panel3Layout.setHorizontalGroup(
            word1panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word1label3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word1panel3Layout.setVerticalGroup(
            word1panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word1label3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word1panel4.setBackground(new java.awt.Color(144, 144, 144));
        word1panel4.setMaximumSize(new java.awt.Dimension(50, 50));
        word1panel4.setMinimumSize(new java.awt.Dimension(50, 50));

        word1label4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word1label4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word1panel4Layout = new javax.swing.GroupLayout(word1panel4);
        word1panel4.setLayout(word1panel4Layout);
        word1panel4Layout.setHorizontalGroup(
            word1panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word1label4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word1panel4Layout.setVerticalGroup(
            word1panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word1label4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word1panel5.setBackground(new java.awt.Color(144, 144, 144));
        word1panel5.setMaximumSize(new java.awt.Dimension(50, 50));
        word1panel5.setMinimumSize(new java.awt.Dimension(50, 50));

        word1label5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word1label5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word1panel5Layout = new javax.swing.GroupLayout(word1panel5);
        word1panel5.setLayout(word1panel5Layout);
        word1panel5Layout.setHorizontalGroup(
            word1panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word1label5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word1panel5Layout.setVerticalGroup(
            word1panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word1panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word1label5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word2panel1.setBackground(new java.awt.Color(144, 144, 144));

        word2label1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word2label1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word2panel1Layout = new javax.swing.GroupLayout(word2panel1);
        word2panel1.setLayout(word2panel1Layout);
        word2panel1Layout.setHorizontalGroup(
            word2panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word2panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(word2label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word2panel1Layout.setVerticalGroup(
            word2panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word2panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word2label1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word2panel2.setBackground(new java.awt.Color(144, 144, 144));

        word2label2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word2label2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word2panel2Layout = new javax.swing.GroupLayout(word2panel2);
        word2panel2.setLayout(word2panel2Layout);
        word2panel2Layout.setHorizontalGroup(
            word2panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word2panel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word2label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word2panel2Layout.setVerticalGroup(
            word2panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word2panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word2label2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word2panel3.setBackground(new java.awt.Color(144, 144, 144));

        word2label3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word2label3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word2panel3Layout = new javax.swing.GroupLayout(word2panel3);
        word2panel3.setLayout(word2panel3Layout);
        word2panel3Layout.setHorizontalGroup(
            word2panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word2panel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word2label3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word2panel3Layout.setVerticalGroup(
            word2panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word2panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word2label3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word2panel4.setBackground(new java.awt.Color(144, 144, 144));

        word2label4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word2label4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word2panel4Layout = new javax.swing.GroupLayout(word2panel4);
        word2panel4.setLayout(word2panel4Layout);
        word2panel4Layout.setHorizontalGroup(
            word2panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word2panel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word2label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word2panel4Layout.setVerticalGroup(
            word2panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word2panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word2label4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word2panel5.setBackground(new java.awt.Color(144, 144, 144));

        word2label5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word2label5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word2panel5Layout = new javax.swing.GroupLayout(word2panel5);
        word2panel5.setLayout(word2panel5Layout);
        word2panel5Layout.setHorizontalGroup(
            word2panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word2panel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word2label5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word2panel5Layout.setVerticalGroup(
            word2panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word2panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word2label5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word3panel1.setBackground(new java.awt.Color(144, 144, 144));

        word3label1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word3label1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word3panel1Layout = new javax.swing.GroupLayout(word3panel1);
        word3panel1.setLayout(word3panel1Layout);
        word3panel1Layout.setHorizontalGroup(
            word3panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word3label1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word3panel1Layout.setVerticalGroup(
            word3panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word3panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word3label1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word3panel2.setBackground(new java.awt.Color(144, 144, 144));

        word3label2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word3label2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word3panel2Layout = new javax.swing.GroupLayout(word3panel2);
        word3panel2.setLayout(word3panel2Layout);
        word3panel2Layout.setHorizontalGroup(
            word3panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word3panel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word3label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word3panel2Layout.setVerticalGroup(
            word3panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word3label2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word3panel3.setBackground(new java.awt.Color(144, 144, 144));

        word3label3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word3label3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word3panel3Layout = new javax.swing.GroupLayout(word3panel3);
        word3panel3.setLayout(word3panel3Layout);
        word3panel3Layout.setHorizontalGroup(
            word3panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word3label3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word3panel3Layout.setVerticalGroup(
            word3panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word3label3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word3panel4.setBackground(new java.awt.Color(144, 144, 144));

        word3label4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word3label4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word3panel4Layout = new javax.swing.GroupLayout(word3panel4);
        word3panel4.setLayout(word3panel4Layout);
        word3panel4Layout.setHorizontalGroup(
            word3panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word3panel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word3label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word3panel4Layout.setVerticalGroup(
            word3panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word3label4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word3panel5.setBackground(new java.awt.Color(144, 144, 144));

        word3label5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word3label5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word3panel5Layout = new javax.swing.GroupLayout(word3panel5);
        word3panel5.setLayout(word3panel5Layout);
        word3panel5Layout.setHorizontalGroup(
            word3panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word3label5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word3panel5Layout.setVerticalGroup(
            word3panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word3panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word3label5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word4panel1.setBackground(new java.awt.Color(144, 144, 144));

        word4label1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word4label1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word4panel1Layout = new javax.swing.GroupLayout(word4panel1);
        word4panel1.setLayout(word4panel1Layout);
        word4panel1Layout.setHorizontalGroup(
            word4panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word4panel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word4label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word4panel1Layout.setVerticalGroup(
            word4panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word4panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word4label1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word4panel2.setBackground(new java.awt.Color(144, 144, 144));

        word4label2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word4label2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word4panel2Layout = new javax.swing.GroupLayout(word4panel2);
        word4panel2.setLayout(word4panel2Layout);
        word4panel2Layout.setHorizontalGroup(
            word4panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word4panel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word4label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word4panel2Layout.setVerticalGroup(
            word4panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word4panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word4label2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word4panel3.setBackground(new java.awt.Color(144, 144, 144));

        word4label3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word4label3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word4panel3Layout = new javax.swing.GroupLayout(word4panel3);
        word4panel3.setLayout(word4panel3Layout);
        word4panel3Layout.setHorizontalGroup(
            word4panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word4panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word4label3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word4panel3Layout.setVerticalGroup(
            word4panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word4panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word4label3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word4panel4.setBackground(new java.awt.Color(144, 144, 144));

        word4label4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word4label4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word4panel4Layout = new javax.swing.GroupLayout(word4panel4);
        word4panel4.setLayout(word4panel4Layout);
        word4panel4Layout.setHorizontalGroup(
            word4panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word4panel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word4label4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word4panel4Layout.setVerticalGroup(
            word4panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word4panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word4label4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word4panel5.setBackground(new java.awt.Color(144, 144, 144));

        word4label5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word4label5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word4panel5Layout = new javax.swing.GroupLayout(word4panel5);
        word4panel5.setLayout(word4panel5Layout);
        word4panel5Layout.setHorizontalGroup(
            word4panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word4panel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word4label5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word4panel5Layout.setVerticalGroup(
            word4panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word4panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word4label5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word5panel1.setBackground(new java.awt.Color(144, 144, 144));

        word5label1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word5label1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word5panel1Layout = new javax.swing.GroupLayout(word5panel1);
        word5panel1.setLayout(word5panel1Layout);
        word5panel1Layout.setHorizontalGroup(
            word5panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word5panel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word5label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word5panel1Layout.setVerticalGroup(
            word5panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word5panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word5label1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word5panel2.setBackground(new java.awt.Color(144, 144, 144));

        word5label2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word5label2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word5panel2Layout = new javax.swing.GroupLayout(word5panel2);
        word5panel2.setLayout(word5panel2Layout);
        word5panel2Layout.setHorizontalGroup(
            word5panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word5panel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word5label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word5panel2Layout.setVerticalGroup(
            word5panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word5panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word5label2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word5panel3.setBackground(new java.awt.Color(144, 144, 144));

        word5label3.setBackground(new java.awt.Color(144, 144, 144));
        word5label3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word5label3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word5panel3Layout = new javax.swing.GroupLayout(word5panel3);
        word5panel3.setLayout(word5panel3Layout);
        word5panel3Layout.setHorizontalGroup(
            word5panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word5panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word5label3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word5panel3Layout.setVerticalGroup(
            word5panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word5panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word5label3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word5panel4.setBackground(new java.awt.Color(144, 144, 144));

        word5label4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word5label4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word5panel4Layout = new javax.swing.GroupLayout(word5panel4);
        word5panel4.setLayout(word5panel4Layout);
        word5panel4Layout.setHorizontalGroup(
            word5panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word5panel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word5label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word5panel4Layout.setVerticalGroup(
            word5panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word5panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word5label4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word5panel5.setBackground(new java.awt.Color(144, 144, 144));

        word5label5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word5label5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word5panel5Layout = new javax.swing.GroupLayout(word5panel5);
        word5panel5.setLayout(word5panel5Layout);
        word5panel5Layout.setHorizontalGroup(
            word5panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word5panel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(word5label5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
        word5panel5Layout.setVerticalGroup(
            word5panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word5panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word5label5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word6panel1.setBackground(new java.awt.Color(144, 144, 144));

        word6label1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word6label1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word6panel1Layout = new javax.swing.GroupLayout(word6panel1);
        word6panel1.setLayout(word6panel1Layout);
        word6panel1Layout.setHorizontalGroup(
            word6panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word6label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word6panel1Layout.setVerticalGroup(
            word6panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word6label1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word6panel2.setBackground(new java.awt.Color(144, 144, 144));

        word6label2.setBackground(new java.awt.Color(144, 144, 144));
        word6label2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word6label2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word6panel2Layout = new javax.swing.GroupLayout(word6panel2);
        word6panel2.setLayout(word6panel2Layout);
        word6panel2Layout.setHorizontalGroup(
            word6panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word6label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word6panel2Layout.setVerticalGroup(
            word6panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word6panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word6label2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word6panel3.setBackground(new java.awt.Color(144, 144, 144));

        word6label3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word6label3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word6panel3Layout = new javax.swing.GroupLayout(word6panel3);
        word6panel3.setLayout(word6panel3Layout);
        word6panel3Layout.setHorizontalGroup(
            word6panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word6label3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word6panel3Layout.setVerticalGroup(
            word6panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word6label3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word6panel4.setBackground(new java.awt.Color(144, 144, 144));

        word6label4.setBackground(new java.awt.Color(144, 144, 144));
        word6label4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word6label4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word6panel4Layout = new javax.swing.GroupLayout(word6panel4);
        word6panel4.setLayout(word6panel4Layout);
        word6panel4Layout.setHorizontalGroup(
            word6panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word6label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word6panel4Layout.setVerticalGroup(
            word6panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word6label4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        word6panel5.setBackground(new java.awt.Color(144, 144, 144));

        word6label5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        word6label5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout word6panel5Layout = new javax.swing.GroupLayout(word6panel5);
        word6panel5.setLayout(word6panel5Layout);
        word6panel5Layout.setHorizontalGroup(
            word6panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, word6panel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(word6label5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        word6panel5Layout.setVerticalGroup(
            word6panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(word6panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word6label5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField1.setBackground(new java.awt.Color(144, 144, 144));
        jTextField1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(144, 144, 144));
        HomeButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setText("RESTART");
        HomeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        HomeButton.setBorderPainted(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        EnterButton1.setBackground(new java.awt.Color(144, 144, 144));
        EnterButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        EnterButton1.setForeground(new java.awt.Color(255, 255, 255));
        EnterButton1.setText("ENTER");
        EnterButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EnterButton1.setBorderPainted(false);
        EnterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(word3panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word3panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word3panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word3panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word3panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(word4panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word4panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word4panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word4panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word4panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(word5panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word5panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word5panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word5panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(word5panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(word6panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word6panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(word6panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(word6panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word6panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EnterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(word1panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(word2panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(word2panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word2panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word2panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word2panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(word1panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word1panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word1panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(word1panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word1panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word1panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(word1panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word1panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word1panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word2panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word2panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word2panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word2panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word2panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word3panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word3panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word3panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word3panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word3panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word4panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word4panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word4panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word4panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word4panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word5panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word5panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word5panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word5panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word5panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word6panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word6panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word6panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word6panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word6panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        WalmartWordle.homeButtonClicked();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void EnterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButton1ActionPerformed
        // TODO add your handling code here:
        if(!WalmartWordle.wordInDict(jTextField1.getText().toLowerCase())){
        
            jDialog1.setBounds(getX() + 85, getY() + 225, 260, 100);
            jDialog1.setVisible(true);
        
        }
        else{
        
            WalmartWordle.enterButtonClicked(jTextField1.getText().toLowerCase());
            if(lost){
            
                jDialog2.setBounds(getX() + 100, getY() + 225, 230, 100);
                jDialog2.setVisible(true);
            
            }
            
        }
        
    }//GEN-LAST:event_EnterButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton1;
    private javax.swing.JButton HomeButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel word1label1;
    public javax.swing.JLabel word1label2;
    public javax.swing.JLabel word1label3;
    public javax.swing.JLabel word1label4;
    public javax.swing.JLabel word1label5;
    public javax.swing.JPanel word1panel1;
    public javax.swing.JPanel word1panel2;
    public javax.swing.JPanel word1panel3;
    public javax.swing.JPanel word1panel4;
    public javax.swing.JPanel word1panel5;
    public javax.swing.JLabel word2label1;
    public javax.swing.JLabel word2label2;
    public javax.swing.JLabel word2label3;
    public javax.swing.JLabel word2label4;
    public javax.swing.JLabel word2label5;
    public javax.swing.JPanel word2panel1;
    public javax.swing.JPanel word2panel2;
    public javax.swing.JPanel word2panel3;
    public javax.swing.JPanel word2panel4;
    public javax.swing.JPanel word2panel5;
    public javax.swing.JLabel word3label1;
    public javax.swing.JLabel word3label2;
    public javax.swing.JLabel word3label3;
    public javax.swing.JLabel word3label4;
    public javax.swing.JLabel word3label5;
    public javax.swing.JPanel word3panel1;
    public javax.swing.JPanel word3panel2;
    public javax.swing.JPanel word3panel3;
    public javax.swing.JPanel word3panel4;
    public javax.swing.JPanel word3panel5;
    public javax.swing.JLabel word4label1;
    public javax.swing.JLabel word4label2;
    public javax.swing.JLabel word4label3;
    public javax.swing.JLabel word4label4;
    public javax.swing.JLabel word4label5;
    public javax.swing.JPanel word4panel1;
    public javax.swing.JPanel word4panel2;
    public javax.swing.JPanel word4panel3;
    public javax.swing.JPanel word4panel4;
    public javax.swing.JPanel word4panel5;
    public javax.swing.JLabel word5label1;
    public javax.swing.JLabel word5label2;
    public javax.swing.JLabel word5label3;
    public javax.swing.JLabel word5label4;
    public javax.swing.JLabel word5label5;
    public javax.swing.JPanel word5panel1;
    public javax.swing.JPanel word5panel2;
    public javax.swing.JPanel word5panel3;
    public javax.swing.JPanel word5panel4;
    public javax.swing.JPanel word5panel5;
    public javax.swing.JLabel word6label1;
    public javax.swing.JLabel word6label2;
    public javax.swing.JLabel word6label3;
    public javax.swing.JLabel word6label4;
    public javax.swing.JLabel word6label5;
    public javax.swing.JPanel word6panel1;
    public javax.swing.JPanel word6panel2;
    public javax.swing.JPanel word6panel3;
    public javax.swing.JPanel word6panel4;
    public javax.swing.JPanel word6panel5;
    // End of variables declaration//GEN-END:variables
}
